# Generated by Django 4.2.4 on 2023-09-15 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haircrm', '0003_alter_client_data_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='haircrm.client')),
                ('worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='haircrm.worker')),
            ],
        ),
    ]
